package(default_visibility = ["//visibility:public"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "units",
    deps = [
        "@dev_april_corgi//js/common",
        "@dev_april_corgi//js/server:client",
    ],
)
