package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "views",
    deps = [
        "//js/common",
        "//js/corgi",
        "//js/corgi/history",
    ],
)

