package(default_visibility = ["//visibility:public"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "dino",
    deps = [
        "@dev_april_corgi//js/corgi",
        "@dev_april_corgi//js/emu",
    ],
)

