package(default_visibility = [":internal"])

package_group(
    name = "internal",
    packages = [
        "//java/lat/trails/...",
        "//javatests/lat/trails/...",
        "//production/...",
    ],
)
