package(default_visibility = ["//visibility:public"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "map",
    deps = [
        "//js/common",
        "//js/map/models",
        "//js/map/rendering",
        "//java/org/trailcatalog/s2",
        "//js/corgi",
        "//js/corgi/history",
    ],
)

