package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "map",
    deps = [
        "//java/org/trailcatalog/client/common",
        "//js/map/models",
        "//js/map/rendering",
        "//java/org/trailcatalog/s2",
        "//js/corgi",
        "//js/corgi/history",
    ],
)

