[[actions]]
type = "create_table"
name = "users"
primary_key = ["id"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "oidc_issuer"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "oidc_id"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "display_name"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "enabled"
  nullable = false
  type = "BOOLEAN"

  [[actions.columns]]
  name = "last_login"
  nullable = false
  type = "TIMESTAMPTZ"

[[actions]]
type = "add_index"
table = "users"

  [actions.index]
  name = "users_by_oidc_issuer_oidc_id"
  columns = ["oidc_issuer", "oidc_id"]
  unique = true

[[actions]]
type = "create_table"
name = "collections"
primary_key = ["id"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "creator"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "name"
  nullable = false
  type = "TEXT"

  [[actions.foreign_keys]]
  columns = ["creator"]
  referenced_table = "users"
  referenced_columns = ["id"]

[[actions]]
type = "add_index"
table = "collections"

  [actions.index]
  name = "collections_by_creator"
  columns = ["creator"]

[[actions]]
type = "create_table"
name = "lines"
primary_key = ["id"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "collection"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "cell"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "data"
  nullable = false
  type = "JSONB"

  [[actions.columns]]
  name = "lat_lng_degrees"
  nullable = false
  type = "BYTEA"

  [[actions.foreign_keys]]
  columns = ["collection"]
  referenced_table = "collections"
  referenced_columns = ["id"]

[[actions]]
type = "add_index"
table = "lines"

  [actions.index]
  name = "lines_by_collection"
  columns = ["collection"]

[[actions]]
type = "create_table"
name = "polygons"
primary_key = ["id"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "collection"
  nullable = false
  type = "UUID"

  [[actions.columns]]
  name = "cell"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "data"
  nullable = false
  type = "JSONB"

  [[actions.columns]]
  name = "s2_polygon"
  nullable = false
  type = "BYTEA"

  [[actions.foreign_keys]]
  columns = ["collection"]
  referenced_table = "collections"
  referenced_columns = ["id"]

[[actions]]
type = "add_index"
table = "polygons"

  [actions.index]
  name = "polygons_by_collection"
  columns = ["collection"]

[[actions]]
type = "custom"

start = """
  INSERT INTO users (id, oidc_issuer, oidc_id, display_name, enabled, last_login)
  VALUES (
    '00000000-0000-0000-0000-000000000000',
    'https://trails.lat',
    '0',
    'trails.lat',
    FALSE,
    '1969-12-31 23:00:00-08'
  );
"""

abort = """
  DELETE FROM users WHERE id = '00000000-0000-0000-0000-000000000000';
"""
