package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "models",
    deps = [
        "//java/org/trailcatalog/client/common",
        "//js/map2/common",
    ],
)

