package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "layers",
    deps = [
        "//js/common",
        "//js/corgi",
        "//java/org/trailcatalog/client/data",
        "//java/org/trailcatalog/client/map",
        "//java/org/trailcatalog/client/map/common",
        "//java/org/trailcatalog/client/map/models",
        "//java/org/trailcatalog/client/map/rendering",
        "//java/org/trailcatalog/client/models",
        "//java/org/trailcatalog/client/workers:ts",
        "//java/org/trailcatalog/models:models-ts",
    ],
)

