[[actions]]
type = "create_table"
name = "active_epoch"
primary_key = ["epoch"]

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

[[actions]]
type = "create_table"
name = "geofabrik_sources"
primary_key = ["path"]

  [[actions.columns]]
  name = "path"
  nullable = false
  type = "TEXT"
