[[actions]]
type = "create_table"
name = "digital_elevation_models"
primary_key = ["namespace", "id"]

  [[actions.columns]]
  name = "namespace"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "date"
  nullable = false
  type = "TIMESTAMPTZ"

  [[actions.columns]]
  name = "resolution_radians"
  nullable = false
  type = "DOUBLE PRECISION"

  [[actions.columns]]
  name = "lat_bound_degrees"
  nullable = false
  type = "INT4RANGE"

  [[actions.columns]]
  name = "lng_bound_degrees"
  nullable = false
  type = "INT4RANGE"

  [[actions.columns]]
  name = "url"
  nullable = false
  type = "TEXT"

[[actions]]
type = "add_index"
table = "digital_elevation_models"

  [actions.index]
  name = "digital_elevation_models_by_lat_lng_idx"
  columns = ["lat_bound_degrees", "lng_bound_degrees"]
  type = "gist"

[[actions]]
type = "create_table"
name = "path_elevations"
primary_key = ["id", "version"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "version"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "down_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "up_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "height_samples_10m_meters"
  nullable = false
  type = "BYTEA"

[[actions]]
type = "add_index"
table = "path_elevations"

  [actions.index]
  name = "path_elevations_by_id_idx"
  columns = ["id"]
