# Latlngs are stored as integer degrees in E7 precision (accurate to 11.1 mm.)

[[actions]]
type = "create_table"
name = "boundaries"
primary_key = ["id", "epoch"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "type"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "cell"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "name"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "s2_polygon"
  nullable = false
  type = "BYTEA"

  [[actions.columns]]
  name = "source_relation"
  nullable = false
  type = "BIGINT"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "boundaries"

  [actions.index]
  name = "boundaries_by_cell_epoch_idx"
  columns = ["cell", "epoch"]
  concurrently = false

[[actions]]
type = "create_table"
name = "boundaries_in_boundaries"
primary_key = ["child_id", "parent_id", "epoch"]

  [[actions.columns]]
  name = "child_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "parent_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "boundaries_in_boundaries"

  [actions.index]
  name = "boundaries_in_boundaries_by_child_id_epoch_idx"
  columns = ["child_id", "epoch"]
  concurrently = false

[[actions]]
type = "create_table"
name = "paths"
primary_key = ["id", "epoch"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "type"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "cell"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "lat_lng_degrees"
  nullable = false
  type = "BYTEA"

  [[actions.columns]]
  name = "source_way"
  nullable = false
  type = "BIGINT"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "paths"

  [actions.index]
  name = "paths_by_cell_epoch_idx"
  columns = ["cell", "epoch"]
  concurrently = false

# This table is necessary because it allows us to filter out paths that are not part of a trail when
# loading data.
[[actions]]
type = "create_table"
name = "paths_in_trails"
primary_key = ["path_id", "trail_id", "epoch"]

  [[actions.columns]]
  name = "path_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "trail_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "paths_in_trails"

  [actions.index]
  name = "paths_in_trails_by_path_id_epoch_idx"
  columns = ["path_id", "epoch"]
  concurrently = false

[[actions]]
type = "create_table"
name = "trails"
primary_key = ["id", "epoch"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "type"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "cell"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "name"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "path_ids"
  nullable = false
  type = "BYTEA"

  [[actions.columns]]
  name = "bound_degrees_e7"
  nullable = false
  type = "BYTEA"

  [[actions.columns]]
  name = "marker_degrees_e7"
  nullable = false
  type = "BYTEA"

  [[actions.columns]]
  name = "elevation_down_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "elevation_up_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "length_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "source_relation"
  nullable = true
  type = "BIGINT"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "trails"

  [actions.index]
  name = "trails_by_cell_epoch_idx"
  columns = ["cell", "epoch"]
  concurrently = false

[[actions]]
type = "create_table"
name = "trails_in_boundaries"
primary_key = ["boundary_id", "trail_id", "epoch"]

  [[actions.columns]]
  name = "boundary_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "trail_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "trails_in_boundaries"

  [actions.index]
  name = "trails_in_boundaries_by_boundary_id_epoch_idx"
  columns = ["boundary_id", "epoch"]
  concurrently = false

[[actions]]
type = "add_index"
table = "trails_in_boundaries"

  [actions.index]
  name = "trails_in_boundaries_by_trail_id_epoch_idx"
  columns = ["trail_id", "epoch"]
  concurrently = false
