[[actions]]
type = "remove_table"
table = "path_elevations"

[[actions]]
type = "create_table"
name = "path_elevations"
primary_key = ["id", "epoch"]

  [[actions.columns]]
  name = "id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "down_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "up_meters"
  nullable = false
  type = "REAL"

  [[actions.columns]]
  name = "height_samples_10m_meters"
  nullable = false
  type = "BYTEA"

