[[actions]]
type = "create_table"
name = "trail_facts"

  [[actions.columns]]
  name = "trail_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "epoch"
  nullable = false
  type = "INT"

  [[actions.columns]]
  name = "predicate"
  nullable = false
  type = "TEXT"

  [[actions.columns]]
  name = "value"
  nullable = false
  type = "JSONB"

  [actions.partition_by]
  list = ["epoch"]

[[actions]]
type = "add_index"
table = "trail_facts"

  [actions.index]
  name = "trail_facts_by_trail_id_epoch_idx"
  columns = ["trail_id", "epoch"]
  concurrently = false

