[[actions]]
type = "custom"

start = """
  CREATE OR REPLACE FUNCTION enumADescendsB(a integer, b integer, size integer) RETURNS boolean AS '
    SELECT
        a = b
        OR (a - 1) / size = b
        OR ((a - 1) / size - 1) / size = b
        OR (((a - 1) / size - 1) / size - 1) / size = b
        OR ((((a - 1) / size - 1) / size - 1) / size - 1) / size = b
        OR (((((a - 1) / size - 1) / size - 1) / size - 1) / size - 1) / size = b
        OR ((((((a - 1) / size - 1) / size - 1) / size - 1) / size - 1) / size - 1) / size = b
  '
  LANGUAGE SQL
  IMMUTABLE;
"""

abort = """
  DROP FUNCTION IF EXISTS enumADescendsB;
"""

