package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "data",
    deps = [
        "//js/common",
        "//js/corgi",
        "//java/org/trailcatalog/client/models",
        "//java/org/trailcatalog/client/workers:ts",
    ],
)

