[[actions]]
type = "add_column"
table = "routes"

up = "0"

	[actions.column]
	name = "mercator_x"
  nullable = false
	type = "DOUBLE PRECISION"

[[actions]]
type = "add_column"
table = "routes"

up = "0"

	[actions.column]
	name = "mercator_y"
  nullable = false
	type = "DOUBLE PRECISION"
