[[actions]]
type = "create_table"
name = "boundaries_containing_trails"
primary_key = ["boundary_id", "trail_id"]

  [[actions.columns]]
  name = "boundary_id"
  nullable = false
  type = "BIGINT"

  [[actions.columns]]
  name = "trail_id"
  nullable = false
  type = "BIGINT"

  [[actions.foreign_key]]
  columns = ["boundary_id"]
  referenced_table = "boundaries"
  referenced_columns = ["id"]

  [[actions.foreign_key]]
  columns = ["trail_id"]
  referenced_table = "trails"
  referenced_columns = ["id"]
