package(default_visibility = ["//java/org/trailcatalog:internal"])

proto_library(
    name = "encoding_proto",
    srcs = ["encoding.proto"],
)

java_proto_library(
    name = "encoding_java_proto",
    deps = [":encoding_proto"],
)
