package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "rendering",
    deps = [
        "//java/org/trailcatalog/client/common",
        "//java/org/trailcatalog/client/map/models",
    ],
)

