package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "rendering",
    deps = [
        "//:node_modules/@mapbox/tiny-sdf",
        "//js/map/common",
        "//js/map/models",
    ],
)

