FROM docker.io/debian:testing-slim
RUN apt-get update \
    && apt-get install --no-install-recommends --yes \
        ca-certificates \
        curl \
        gnupg \
        nginx \
        openjdk-25-jre-headless \
        xz-utils \
    && apt-get clean \
    && curl -L https://nodejs.org/dist/v22.16.0/node-v22.16.0-linux-x64.tar.xz | tar -xvJf -
ENV NODEJS_DIR /node-v22.16.0-linux-x64
ARG NGINX_CONF
COPY $NGINX_CONF /app/nginx.conf
COPY serve.sh /app/serve.sh
COPY frontend_pkg.tar ./
RUN tar -xvf ./frontend_pkg.tar && rm ./frontend_pkg.tar
RUN useradd app --create-home
RUN chown -R app:app /var/lib/nginx
USER app:app
CMD /app/serve.sh
