package(default_visibility = ["//java/org/trailcatalog:internal"])

load("//build_defs:ts.bzl", "tc_ts_project")

tc_ts_project(
    name = "common",
    deps = [
        "//java/org/trailcatalog/s2",
        "//js/corgi",
        "//js/corgi/history",
        "//js/dino",
        "//js/map/common",
    ],
)

